import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "NextApp",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <Link href="/">Home</Link>
          <br />
          <Link href="/posts">Posts</Link>
          <br />
          <Link href="/articles">Articles</Link>
          <br />
          <Link href="/jsonposts">jsonposts</Link>
          <br />
          <Link href="/articles/article1">Articles/article1</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
